export const USER_TABLE_PARAMS_UPDATE = 'USER_TABLE_PARAMS_UPDATE';
export const USER_TABLE_GET = 'USER_TABLE_GET';
export const USER_TABLE_GET_SUCCESS = 'USER_TABLE_GET_SUCCESS';
export const USER_TABLE_GET_FAIL = 'USER_TABLE_GET_FAIL';
export const USER_TABLE_RELOAD = 'USER_TABLE_RELOAD';
export const USER_TOOLBAR_SEARCH_KEYWORDS_UPDATE = 'USER_TOOLBAR_SEARCH_KEYWORDS_UPDATE';

export const USER_EDITOR_ADD = 'USER_EDITOR_ADD';
export const USER_EDITOR_SAVE_FIELDS = 'USER_EDITOR_SAVE_FIELDS';
export const USER_EDITOR_SUBMIT = 'USER_EDITOR_SUBMIT';
export const USER_EDITOR_SUBMIT_SUCCESS = 'USER_EDITOR_SUBMIT_SUCCESS';
export const USER_EDITOR_SUBMIT_FAIL = 'USER_EDITOR_SUBMIT_FAIL';
export const USER_EDITOR_CLOSE = 'USER_EDITOR_CLOSE';
