export const USER_TABLE_PARAMS_UPDATE = 'USER_TABLE_PARAMS_UPDATE';
export const USER_TABLE_GET = 'USER_TABLE_GET';
export const USER_TABLE_GET_SUCCESS = 'USER_TABLE_GET_SUCCESS';
export const USER_TABLE_GET_FAIL = 'USER_TABLE_GET_FAIL';
export const USER_TABLE_RELOAD = 'USER_TABLE_RELOAD';
export const USER_TOOLBAR_SEARCH_KEYWORDS_UPDATE = 'USER_TOOLBAR_SEARCH_KEYWORDS_UPDATE';
